<?php declare( strict_types = 1 );
/**
 * Project: SMPlatform
 * File: CompanyUserIdentity.php
 * Create: 2018/4/9
 * Author: Hugh.Lee
 * Email: umbrellahughlee@gmail.com
 * Copyright: SMBC Inc.
 */

namespace SMPlatform\PLATFORM\MODEL\IDENTITY;

use SMPlatform\PLATFORM\MODEL\DATA\UserIdentity;
use UmbServer\SwooleFramework\LIBRARY\UTIL\Serialize;

/**
 * 公司认证类
 * Class CompanyUserIdentity
 * @package SMPlatform\PLATFORM\MODEL\IDENTITY
 */
class CompanyUserIdentity extends UserIdentity
{
    public $company_name; //企业名称
    public $organization_no; //企业机构编号
    
    /**
     * 释放数据
     * @throws \UmbServer\SwooleFramework\LIBRARY\ERROR\UtilError
     */
    public
    function decodeData()
    {
        $data_decode = Serialize::decode( $this->encode_data, $this->encode_type );
        foreach ( $data_decode as $key => $value ) {
            $this->$key = $value;
        }
    }
    
    /**
     * 重写update
     * @param bool $is_push
     * @return bool
     * @throws \UmbServer\SwooleFramework\LIBRARY\ERROR\UtilError
     */
    public
    function update( $is_push = true )
    {
        $this->encodeData();
        return parent::update( $is_push ); // TODO: Change the autogenerated stub
    }
    
    /**
     * 设置encode数据
     * @throws \UmbServer\SwooleFramework\LIBRARY\ERROR\UtilError
     */
    private
    function encodeData()
    {
        $data                  = new \stdClass();
        $data->company_name    = $this->company_name;
        $data->organization_no = $this->organization_no;
        $data_encode           = Serialize::encode( $data, $this->encode_type );
        $this->encode_data     = $data_encode;
    }
}