<?php declare( strict_types = 1 );
/**
 * Project: SMPlatform
 * File: PersonalUserIdentity.php
 * Create: 2018/4/9
 * Author: Hugh.Lee
 * Email: umbrellahughlee@gmail.com
 * Copyright: SMBC Inc.
 */

namespace SMPlatform\PLATFORM\MODEL\IDENTITY;

use SMPlatform\PLATFORM\MODEL\DATA\UserIdentity;
use UmbServer\SwooleFramework\EXTRA\ENUM\_Nationality;
use UmbServer\SwooleFramework\LIBRARY\UTIL\Serialize;

/**
 * 个人用户认证类
 * Class PersonalUserIdentity
 * @package SMPlatform\PLATFORM\MODEL\IDENTITY
 */
class PersonalUserIdentity extends UserIdentity
{
    public $real_name; //真实姓名
    public $cellphone; //手机号
    public $nationality = _Nationality::CHINA; //国籍
    public $id_card_no; //身份证号
    
    /**
     * 释放数据
     * @throws \UmbServer\SwooleFramework\LIBRARY\ERROR\UtilError
     */
    public
    function decodeData()
    {
        $data_decode = Serialize::decode( $this->encode_data, $this->encode_type );
        foreach ( $data_decode as $key => $value ) {
            $this->$key = $value;
        }
    }
    
    /**
     * 重写update
     * @param bool $is_push
     * @return bool
     * @throws \UmbServer\SwooleFramework\LIBRARY\ERROR\UtilError
     */
    public
    function update( $is_push = true )
    {
        $this->encodeData();
        return parent::update( $is_push ); // TODO: Change the autogenerated stub
    }
    
    /**
     * 设置encode数据
     * @throws \UmbServer\SwooleFramework\LIBRARY\ERROR\UtilError
     */
    private
    function encodeData()
    {
        $data              = new \stdClass();
        $data->real_name   = $this->real_name;
        $data->cellphone   = $this->cellphone;
        $data->nationality = $this->nationality;
        $data->id_card_no  = $this->id_card_no;
        $data_encode       = Serialize::encode( $data, $this->encode_type );
        $this->encode_data = $data_encode;
    }
}